#!/bin/bash

stream="$1"
cleanup() {
    kill -KILL "$ffmpegpid"
    i=0
    while [ -d "/var/www/$stream$i" ]; do
        (( i++ ))
    done
    mkdir "/var/www/$stream$i"
    mv /var/www/*.ts "/var/www/$stream$i/"
    mv /var/www/*.m3u8 "/var/www/$stream$i/"
}

ffmpeg -re -i "rtmp://127.0.0.1/live/$1" -c:v copy -c:a libfdk_aac -b:a 128k -bsf:v h264_mp4toannexb -hls_time 8 -f hls /var/www/$1.m3u8 &

ffmpegpid=$!

trap cleanup TERM

wait
