#!/bin/bash

cd /var/repos

stream="$1"
i=$(date +"%s")

cleanup() {
    kill -TERM "$fblivepid"
    kill -TERM "$ffmpegpid"
    sleep 2
    kill -TERM "$ffmpegpid"
}

rm /var/www/*.ts
rm /var/www/*.m3u8

which ffmpeg
ffmpeg -i "rtmp://127.0.0.1/live/$1" -c:v copy -c:a aac -strict -2 -b:a 128k -bsf:v h264_mp4toannexb -hls_list_size 5 -hls_time 8 -f hls /var/www/$1.m3u8 &
ffmpegpid=$!

node /var/repos/create-stream.js "rtmp://127.0.0.1/live/$1" &
fblivepid=$!

trap cleanup TERM

wait
